export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_COMPETITIONS = 'GET_COMPETITIONS';
export const GET_COMPETITION = 'GET_COMPETITION';
export const ADD_COMPETITION = 'ADD_COMPETITION';
export const DELETE_COMPETITION = 'DELETE_COMPETITION';
export const COMPETITIONS_LOADING = 'COMPETITIONS_LOADING';

export const GET_ROUNDS = 'GET_ROUNDS';
export const ADD_ROUND = 'ADD_ROUND';
export const DELETE_ROUND = 'DELETE_ROUND';
export const ROUNDS_LOADING = 'ROUNDS_LOADING';

export const GET_USER = 'GET_USER';
export const CONNECT_STRAVA = 'CONNECT_STRAVA';
export const DISCONNECT_STRAVA = 'DISCONNECT_STRAVA';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const GET_LEADERBOARD = 'GET_LEADERBOARD';
export const LEADERBOARD_LOADING = 'LEADERBOARD_LOADING';